name:                LibraryApi
version:             0.1.0.0
github:              "terminalnode/libapi-hs"
license:             BSD3
author:              "Alexander Rundberg"
maintainer:          "alexanderrundberg@fastmail.jp"
copyright:           "2023 Alexander Rundberg"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/terminalnode/libapi-hs#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- warp
- persistent
- persistent-postgresql
- persistent-template
- time
- text
- monad-logger
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  LibraryApi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LibraryApi

tests:
  LibraryApi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LibraryApi
